services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    restart: no
    volumes:
      - "./data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb:
    image: "aaronshaf/dynamodb-admin"
    container_name: dynamodb-admin
    depends_on:
      - dynamodb-local
    restart: no
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-southeast-1

  fiap-fastfood:
    build: .
    container_name: fiap-fastfood
    depends_on:
      - dynamodb-local
    restart: no
    ports:
      - 8088:8080